/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditPreferences.java
 *
 * Created on Dec 6, 2010, 3:55:36 PM
 */

package nl.lamia.FixTools;

import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.ToolTipManager;
import javax.swing.text.JTextComponent;

/**
 *
 * @author marcel
 */
public class EditPreferences extends javax.swing.JDialog {

    int timeout;
    String ignoreUnexpectedTags,checkDateTags,skipTags,matchMsgType,matchClordid;
    ConfigurationManager cm;

    /** Creates new form EditPreferences */
    public EditPreferences(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Get configuration
        cm=ConfigurationManager.getConfigurationManager();
        //Set time out value
        String toVal=cm.getProperty("ExpectMessageStep.timeout", "10000");
        this.timeout=Integer.parseInt(toVal);
        jSliderTimeout.setValue(this.timeout);
        selTimeout.setText(Integer.toString(jSliderTimeout.getValue()));
        //Set Test Message values
        this.ignoreUnexpectedTags=cm.getProperty("TestMessage.ignoreUnexpectedTags","false");
        if (this.ignoreUnexpectedTags.equalsIgnoreCase("true")) {
            jCheckBoxIgnoreUnexpect.setSelected(true);
        } else {
            jCheckBoxIgnoreUnexpect.setSelected(false);
        };
        this.checkDateTags=cm.getProperty("TestMessage.checkDateTags","false");
        if (this.checkDateTags.equalsIgnoreCase("true")) {
            jCheckBoxCheckDate.setSelected(true);
        } else {
            jCheckBoxCheckDate.setSelected(false);
        };
        skipTags=cm.getProperty("TestMessage.skipTags","");
        jTextFieldIgnoreTags.setText(skipTags);
        this.matchMsgType=cm.getProperty("TestMessage.matchMsgType","true");
        if (this.matchMsgType.equalsIgnoreCase("true")) {
            jCheckBoxMsgType.setSelected(true);
        } else {
            jCheckBoxMsgType.setSelected(false);
        };
        this.matchClordid=cm.getProperty("TestMessage.matchClordid","false");
        if (this.matchClordid.equalsIgnoreCase("true")) {
            jCheckBoxClordid.setSelected(true);
        } else {
            jCheckBoxClordid.setSelected(false);
        };


        //Input verifiers
        InputVerifier verifier = new InputVerifier() {
        public boolean verify(JComponent input) {
                final JTextComponent source = (JTextComponent)input;
                String text = source.getText();
                if (!text.matches("[0-9,]*")) {
                    source.setBackground(Color.red);
                    ToolTipManager.sharedInstance().mouseMoved(
                        new MouseEvent(source, 0, 0, 0,
                        0, 0, // X-Y of the mouse for the tool tip
                        0, false));
                    return false;
                } else {
                    source.setBackground(Color.white);
                    return true;
                }
            }
        };
        jTextFieldIgnoreTags.setInputVerifier(verifier);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFieldIgnoreTags = new javax.swing.JTextField();
        jSliderTimeout = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        selTimeout = new javax.swing.JLabel();
        jCheckBoxCheckDate = new javax.swing.JCheckBox();
        jCheckBoxIgnoreUnexpect = new javax.swing.JCheckBox();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxMsgType = new javax.swing.JCheckBox();
        jCheckBoxClordid = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("General settings");

        jLabel3.setText("Ignore tags");

        jTextFieldIgnoreTags.setText("jTextField1");
        jTextFieldIgnoreTags.setToolTipText("Enter numeric Fix tags separated by commas.");

        jSliderTimeout.setMajorTickSpacing(30000);
        jSliderTimeout.setMaximum(61000);
        jSliderTimeout.setMinimum(1000);
        jSliderTimeout.setMinorTickSpacing(1000);
        jSliderTimeout.setPaintTicks(true);
        jSliderTimeout.setSnapToTicks(true);
        jSliderTimeout.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderTimeoutStateChanged(evt);
            }
        });
        jSliderTimeout.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jSliderTimeoutCaretPositionChanged(evt);
            }
        });

        jLabel4.setText("Wait for answer timeout (ms)");

        selTimeout.setText("jLabel5");

        jCheckBoxCheckDate.setText("Check date tag format");
        jCheckBoxCheckDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCheckDateActionPerformed(evt);
            }
        });

        jCheckBoxIgnoreUnexpect.setText("Ignore unexpected tags");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Match incoming messages on:");

        jCheckBoxMsgType.setText("MsgType (35)");

        jCheckBoxClordid.setText("Clordid (11)");

        jLabel2.setText("Settings for Expect steps:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addContainerGap(313, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 299, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonCancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonOk))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCheckBoxCheckDate)
                            .add(jCheckBoxIgnoreUnexpect))
                        .addContainerGap(280, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextFieldIgnoreTags, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 339, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jSliderTimeout, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(6, 6, 6)
                                .add(selTimeout)))
                        .addContainerGap(29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(21, 21, 21)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jCheckBoxMsgType)
                                    .add(layout.createSequentialGroup()
                                        .add(jCheckBoxClordid)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(jLabel1))
                        .addContainerGap(266, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextFieldIgnoreTags, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jLabel4))
                    .add(jSliderTimeout, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(11, 11, 11)
                        .add(selTimeout)))
                .add(5, 5, 5)
                .add(jCheckBoxCheckDate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jCheckBoxIgnoreUnexpect)
                .add(18, 18, 18)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBoxMsgType)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jCheckBoxClordid)
                .add(42, 42, 42)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonOk)
                    .add(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxCheckDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCheckDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCheckDateActionPerformed

    private void jSliderTimeoutCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSliderTimeoutCaretPositionChanged
        // TODO add your handling code here:
        selTimeout.setText(Integer.toString(jSliderTimeout.getValue()));
    }//GEN-LAST:event_jSliderTimeoutCaretPositionChanged

    private void jSliderTimeoutStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderTimeoutStateChanged
        selTimeout.setText(Integer.toString(jSliderTimeout.getValue()));
    }//GEN-LAST:event_jSliderTimeoutStateChanged

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        //store the changed values
        cm.setProperty("ExpectMessageStep.timeout", Integer.toString(jSliderTimeout.getValue()));
        if (jTextFieldIgnoreTags.getBackground()!=Color.red)
            cm.setProperty("TestMessage.skipTags",jTextFieldIgnoreTags.getText());
        if (jCheckBoxCheckDate.isSelected()){
            cm.setProperty("TestMessage.checkDateTags","true");
        } else {
            cm.setProperty("TestMessage.checkDateTags","false");
        };
        if (jCheckBoxIgnoreUnexpect.isSelected()){
            cm.setProperty("TestMessage.ignoreUnexpectedTags","true");
        } else {
            cm.setProperty("TestMessage.ignoreUnexpectedTags","false");
        };
        if (jCheckBoxClordid.isSelected()){
            cm.setProperty("TestMessage.matchClordid","true");
        } else {
            cm.setProperty("TestMessage.matchClordid","false");
        };
        if (jCheckBoxMsgType.isSelected()){
            cm.setProperty("TestMessage.matchMsgType","true");
        } else {
            cm.setProperty("TestMessage.matchMsgType","false");
        };
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // No changes, flush
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditPreferences dialog = new EditPreferences(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JCheckBox jCheckBoxCheckDate;
    private javax.swing.JCheckBox jCheckBoxClordid;
    private javax.swing.JCheckBox jCheckBoxIgnoreUnexpect;
    private javax.swing.JCheckBox jCheckBoxMsgType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSlider jSliderTimeout;
    private javax.swing.JTextField jTextFieldIgnoreTags;
    private javax.swing.JLabel selTimeout;
    // End of variables declaration//GEN-END:variables

}
