/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Sep 27, 2010, 9:01:35 PM
 */

package nl.lamia.FixTools;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import org.junit.runner.JUnitCore;

/**
 *
 * @author marcel
 */
public class MainWindow extends javax.swing.JFrame {

    private static String VERSION="FixTestDriver\nP.M.Vrolijk\nVersion 1.31\n2011/03/13";

    private static Logger logger = Logger.getLogger(MainWindow.class);
    static {
	PropertyConfigurator.configure("config/log4j.properties");
    }

    private FixEngine fe;
    private ConfigurationManager cm;
    private String testCasesToRun;
    private String testCasesRoot;
    private DefaultTableModel execStatusTbl;

    /** Creates new form MainWindow */
    public MainWindow() {
        logger.info("FixTestDriver starting...");
        logger.info(VERSION);
        //register ourselves for callbacks
        this.cm=ConfigurationManager.getConfigurationManager();
        cm.setMainApp(this);

        fe=FixEngine.getFixEngine();
        initComponents();

        //TODO check icon setting on windows/linux
        //Image im = Toolkit.getDefaultToolkit().getImage("resources/FixIcon.gif");
        //this.setIconImage(im);

        //Retrieve geometry
        cm.getGeometry(this, "MainWindow", "10,10,640,480");

        //exec status:
        execStatusTbl=new DefaultTableModel();
        jTableEngineStatus.setModel(execStatusTbl);

        //Fill the testcases tree
        this.testCasesRoot=cm.getProperty("Application.testcases","testcases");
        loadTestCases(new File(testCasesRoot));
        //initially testcases to run:=testcases root
        this.testCasesToRun=this.testCasesRoot;
        jTree_testCases.addTreeSelectionListener(new TreeSelectionListener() {
            public void valueChanged(TreeSelectionEvent e) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) e
                    .getPath().getLastPathComponent();
                //System.out.println("You selected "+e.getPath()+" - "+ node);
                if (node.isLeaf()) {
                       testCasesToRun=node.getParent()+File.separator+ node.toString();
                       logger.debug("To run: "+testCasesToRun);
                }else{
                       testCasesToRun=node.toString();
                       logger.debug("To run: "+testCasesToRun);
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree_testCases = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jButtonRunSelected = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTestOutput = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEngineStatus = new javax.swing.JTable();
        jButtonLogoff = new javax.swing.JButton();
        jButtonLogon = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonAddFile = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuLoadTestCases = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemReload = new javax.swing.JMenuItem();
        jMenuItemStartFE = new javax.swing.JMenuItem();
        jMenuItemStopFE = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemTestcaseEdit = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFIXSettings = new javax.swing.JMenuItem();
        jMenuItemPreferences = new javax.swing.JMenuItem();
        jMenuSaveSettings = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemOrderManager = new javax.swing.JMenuItem();
        jMenuItemFixLook = new javax.swing.JMenuItem();
        jMenuItemViewLog = new javax.swing.JMenuItem();
        jMenuItemShowFixLog = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemHelp = new javax.swing.JMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fix Test Driver");

        jTree_testCases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree_testCasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree_testCases);

        jLabel1.setText("Testcase files");

        jButtonRunSelected.setText("Run selected");
        jButtonRunSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunSelectedActionPerformed(evt);
            }
        });

        jLabel2.setText("Engine");

        jTestOutput.setBackground(new java.awt.Color(220, 220, 220));
        jTestOutput.setColumns(20);
        jTestOutput.setEditable(false);
        jTestOutput.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTestOutput.setRows(5);
        jTestOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Test Output"));
        jScrollPane2.setViewportView(jTestOutput);

        jTableEngineStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableEngineStatus);

        jButtonLogoff.setText("logoff");
        jButtonLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoffActionPerformed(evt);
            }
        });

        jButtonLogon.setText("logon");
        jButtonLogon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogonActionPerformed(evt);
            }
        });

        jButtonReset.setText("reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonAddFile.setText("New File");
        jButtonAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFileActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuLoadTestCases.setText("Load testcases...");
        jMenuLoadTestCases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoadTestCasesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLoadTestCases);
        jMenu1.add(jSeparator1);

        jMenuItemReload.setText("Reload engine");
        jMenuItemReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReloadActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemReload);

        jMenuItemStartFE.setText("Start engine");
        jMenuItemStartFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStartFEActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemStartFE);

        jMenuItemStopFE.setText("Stop engine");
        jMenuItemStopFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStopFEActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemStopFE);
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Quit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItemTestcaseEdit.setText("Edit test case...");
        jMenuItemTestcaseEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTestcaseEditActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTestcaseEdit);
        jMenu2.add(jSeparator3);

        jMenuItemFIXSettings.setText("Edit FIX Sessions...");
        jMenuItemFIXSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFIXSettingsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemFIXSettings);

        jMenuItemPreferences.setText("General Settings");
        jMenuItemPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPreferencesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPreferences);

        jMenuSaveSettings.setText("Save settings");
        jMenuSaveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveSettingsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSaveSettings);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tools");

        jMenuItem1.setText("Edit dictionary...");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItemOrderManager.setText("Order manager...");
        jMenuItemOrderManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrderManagerActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemOrderManager);

        jMenuItemFixLook.setText("Analyse FIX msg...");
        jMenuItemFixLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFixLookActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemFixLook);

        jMenuItemViewLog.setText("View log...");
        jMenuItemViewLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewLogActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemViewLog);

        jMenuItemShowFixLog.setText("Show FIX log...");
        jMenuItemShowFixLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShowFixLogActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemShowFixLog);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItemHelp.setText("Manual");
        jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemHelp);

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAbout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(jButtonAddFile)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonDelete)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 368, Short.MAX_VALUE)
                        .add(jButtonRunSelected))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 427, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonLogoff)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonLogon)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonReset))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(54, 54, 54)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jButtonLogoff)
                                    .add(jButtonLogon)
                                    .add(jButtonReset)))
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(12, 12, 12)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButtonAddFile)
                            .add(jButtonDelete)
                            .add(jButtonRunSelected)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {new DictionaryEditor().setVisible(true);}
        });
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {new DictionaryEditor().setVisible(true);}
        });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Quit
        fe.close();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemOrderManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOrderManagerActionPerformed
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {new OrderManagerGui().setVisible(true);}
        });
    }//GEN-LAST:event_jMenuItemOrderManagerActionPerformed

    private void jMenuLoadTestCasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoadTestCasesActionPerformed
        JFileChooser dialog=new JFileChooser();
        dialog.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result=dialog.showOpenDialog(this);
        if (result==JFileChooser.APPROVE_OPTION) {
            File directory=dialog.getSelectedFile();
            loadTestCases(directory);
            cm.setProperty("Application.testcases", directory.getAbsolutePath());
        } else {
            //no change
        }
        
    }//GEN-LAST:event_jMenuLoadTestCasesActionPerformed

    private void jButtonRunSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunSelectedActionPerformed
        //Run only selected tests
        System.setProperty("testcase.dir",testCasesToRun);
        fe.setParentWindow(this);
        Thread t=new Thread(new Runnable() {
            public void run() {
                    JUnitCore core=new JUnitCore();
                    core.addListener(new JunitListener());
                    core.run(FixResponseTest.class);
                }
            });
        t.start();    }//GEN-LAST:event_jButtonRunSelectedActionPerformed

    private void jMenuSaveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveSettingsActionPerformed
        cm.setGeometry(this, "MainWindow");
        cm.saveProperties();

    }//GEN-LAST:event_jMenuSaveSettingsActionPerformed

    private void jTree_testCasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree_testCasesMouseClicked
        if (evt.getClickCount()==2) {
            int selRow = jTree_testCases.getRowForLocation(evt.getX(), evt.getY());
            TreePath selPath = jTree_testCases.getPathForLocation(evt.getX(), evt.getY());
            DefaultMutableTreeNode node=(DefaultMutableTreeNode)selPath.getLastPathComponent();
            if (node.isLeaf()) {
                final String filename=node.getParent()+File.separator+ node.toString();
                //System.out.println("Double click on "+filename);
                java.awt.EventQueue.invokeLater( new Runnable() {
                    public void run() {new FileEditor(filename).setVisible(true);}
                });
            }
        }
    }//GEN-LAST:event_jTree_testCasesMouseClicked

    private void jButtonLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoffActionPerformed
        int sel=this.jTableEngineStatus.getSelectedRow();
        if (sel==-1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a session on the left.", "INFO", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String session=(String)jTableEngineStatus.getModel().getValueAt(sel, 1);
        fe.logout(session);
    }//GEN-LAST:event_jButtonLogoffActionPerformed

    private void jButtonLogonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogonActionPerformed
        int sel=this.jTableEngineStatus.getSelectedRow();
        if (sel==-1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a session on the left.", "INFO", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String session=(String)jTableEngineStatus.getModel().getValueAt(sel, 1);
        fe.logon(session);
    }//GEN-LAST:event_jButtonLogonActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        int sel=this.jTableEngineStatus.getSelectedRow();
        if (sel==-1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a session on the left.", "INFO", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String session=(String)jTableEngineStatus.getModel().getValueAt(sel, 1);
        fe.reset(session);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jMenuItemStartFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStartFEActionPerformed
        fe.start();
    }//GEN-LAST:event_jMenuItemStartFEActionPerformed

    private void jMenuItemStopFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStopFEActionPerformed
        fe.close();
    }//GEN-LAST:event_jMenuItemStopFEActionPerformed

    private void jMenuItemViewLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewLogActionPerformed
        java.awt.EventQueue.invokeLater( new Runnable() {
             public void run() {new FileEditor("logs/testrun.log",false).setVisible(true);}
        });
    }//GEN-LAST:event_jMenuItemViewLogActionPerformed

    private void jButtonAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddFileActionPerformed
        // Based on testCasesToRun hangen we een nieuwe file in.
        // Deze initialiseren we met een commentaar regel, waarna we de editor openen.
        String newFile="";
        if (new File(testCasesToRun).isDirectory()) {
            newFile=testCasesToRun;
        } else {
            newFile=new File(testCasesToRun).getParent();
        }
        String name=JOptionPane.showInputDialog(this, "Give the name of the new testfile\n"
                , "newTest", JOptionPane.OK_CANCEL_OPTION);
        if (name==null) return;
        if (!name.endsWith(".def")) name+=".def";
        newFile+=File.separator+name;
        //test whether new file exists:
        if (new File(newFile).exists()) {
            JOptionPane.showMessageDialog(this, "File "+newFile+"\nalready exists, please try again."
                ,"Error" ,JOptionPane.OK_OPTION);
        }
        System.out.println("New file to create "+newFile);
        Boolean r=createFile(newFile, "#Example def file\niCONNECT <Session>\n"
                + "I8=FIX.4.2|9=136|35=D|34=40|49=BANZAI|\neDISCONNECT\n");
        //On success reload the treeview and open the file for editing
        if (r) {
            loadTestCases(new File(testCasesRoot));
            final String createdfile=""+newFile;
            java.awt.EventQueue.invokeLater( new Runnable() {
                public void run() {new FileEditor(createdfile).setVisible(true);}
            });
        } 
    }//GEN-LAST:event_jButtonAddFileActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        File toBeDeleted=new File(testCasesToRun);
        if (toBeDeleted.isDirectory()) {
            JOptionPane.showMessageDialog(this, "Deleting directories is not supported."
            ,"Error" ,JOptionPane.OK_OPTION);
            return;
        }
        int result=JOptionPane.showConfirmDialog(this, "Are you sure you want to permanently delete\n"
                + " "+testCasesToRun+" ?\nThis cannot be undone.","Confirm delete",JOptionPane.OK_CANCEL_OPTION);
        if (result!=JOptionPane.OK_OPTION) {
            return;
        }
        logger.info("Deleting...... "+testCasesToRun);
        if (!toBeDeleted.exists()) {
            JOptionPane.showMessageDialog(this, "File cannot be found."
                ,"Error" ,JOptionPane.OK_OPTION);
            loadTestCases(new File(testCasesRoot));  //apparently there was a mismatch
            return;
        }
        if (!toBeDeleted.canWrite()) {
            JOptionPane.showMessageDialog(this, "File seems to be write protected, sorry."
                ,"Error" ,JOptionPane.OK_OPTION);
            return;
        }
        Boolean ok=toBeDeleted.delete();
        if (ok) loadTestCases(new File(testCasesRoot));
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jMenuItemFixLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFixLookActionPerformed
        MessageEditor dlg=new MessageEditor(this, true, "<Paste your message>", true);
        dlg.showDialog();
    }//GEN-LAST:event_jMenuItemFixLookActionPerformed

    private void jMenuItemFIXSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFIXSettingsActionPerformed
        final String fixSettings=cm.getProperty("FixEngine.configuration","config/FixEngine.cfg");
        java.awt.EventQueue.invokeLater( new Runnable() {
             public void run() {new FileEditor(fixSettings,true).setVisible(true);}
        });
    }//GEN-LAST:event_jMenuItemFIXSettingsActionPerformed

    private void jMenuItemReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReloadActionPerformed
        fe.reloadFixEngine();
        JOptionPane.showMessageDialog(this, "Fixengine settings reloaded from disk\nEngine is currently stopped;\n"
                + "use File - start engine to start.","FixEngine",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemReloadActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(this, VERSION,"About",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed
        JEditorPane help;
        File file=new File("resources/Help.html");
        try {
            help=new JEditorPane("file:///"+file.getAbsolutePath()) {
                @Override
                public boolean getScrollableTracksViewportWidth() { //Workaround for Java bug: Impossible to set max width on
                    return true;                                    //an editor pane: html <p> run in one long line.
                }
            };
            help.setEditable(false);
        } catch (IOException e) {
            logger.error("Can't load help file", e);
            return;
        }
        JScrollPane scroll;
        try {scroll=new JScrollPane(help, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);}
        catch (HeadlessException e) {
            logger.error("Can't create a scroll pane ??",e);
            return;
        }
        scroll.setPreferredSize(new Dimension(800,600));

        //Modal:
        //JOptionPane.showMessageDialog(this, scroll,"Help",JOptionPane.PLAIN_MESSAGE);

        //non modal:
        JOptionPane joppie=new JOptionPane(scroll);
        JDialog myDialog = joppie.createDialog(this, "Help");
        myDialog.setModal(false);
        myDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    private void jMenuItemTestcaseEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTestcaseEditActionPerformed
        TreePath selPath = jTree_testCases.getSelectionPath();
        if (selPath==null) return;
        DefaultMutableTreeNode node=(DefaultMutableTreeNode)selPath.getLastPathComponent();
        if (node.isLeaf()) {
            final String filename=node.getParent()+File.separator+ node.toString();
            //System.out.println("Double click on "+filename);
            java.awt.EventQueue.invokeLater( new Runnable() {
                 public void run() {new FileEditor(filename).setVisible(true);}
            });
        }
    }//GEN-LAST:event_jMenuItemTestcaseEditActionPerformed

    private void jMenuItemShowFixLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShowFixLogActionPerformed
        java.awt.EventQueue.invokeLater( new Runnable() {
             public void run() {new FileEditor("logs/Fixmessages.log",false).setVisible(true);}
        });
    }//GEN-LAST:event_jMenuItemShowFixLogActionPerformed

    private void jMenuItemPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPreferencesActionPerformed
        EditPreferences dialog = new EditPreferences(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemPreferencesActionPerformed

    private Boolean createFile(String filename, String initLine) {
        FileWriter writer = null;
        Boolean succes=true;
        try {
            writer = new FileWriter(filename);
            writer.write(initLine);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
            "Error creating file "+filename, "ERROR", JOptionPane.ERROR_MESSAGE);
            succes=false;
        } finally {
            if (writer != null) {
            try {
                writer.close();
                } catch (IOException x) {
                }
            }
        }
        return succes;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    public void appendTestOutput (String msg) {
        this.jTestOutput.append(msg+"\n");
    }

    public void cleanTestOutput() {
        this.jTestOutput.setText("");
    }

    public void setFixStatus(DefaultTableModel tbl) {
        logger.debug("Received FixEngine update:"+tbl.toString());
        try {
            int selected=this.jTableEngineStatus.getSelectedRow();
            this.execStatusTbl=tbl;
            this.jTableEngineStatus.setModel(execStatusTbl);
            this.jTableEngineStatus.getColumnModel().getColumn(0).setMaxWidth(50);
            this.jTableEngineStatus.getColumnModel().getColumn(2).setMaxWidth(70);
            this.jTableEngineStatus.getColumnModel().getColumn(3).setMaxWidth(70);
            if (selected!=-1) this.jTableEngineStatus.addRowSelectionInterval(selected, selected);
        } catch (Exception ex) {
            logger.warn("Fix Me: Fix engine status update synch error.");
        }
    }

    public void loadTestCases(File dir) {
        //initialize the JTree from the root dir
        DefaultTreeModel model=new DefaultTreeModel(addNodes(null, dir));
        jTree_testCases.setModel(model);

    }

    private DefaultMutableTreeNode addNodes(DefaultMutableTreeNode currentParent, File dir) {
        String path=dir.getPath();
        logger.debug("Scanning dir "+path);
        DefaultMutableTreeNode currentDir=new DefaultMutableTreeNode(path);
        if (currentParent!=null) {
            currentParent.add(currentDir);
        }
        Vector list = new Vector();
        String[] dirList = dir.list();
        for (int i = 0; i < dirList.length; i++) {
            list.addElement(dirList[i]);
            logger.debug("   Item "+dirList[i].toString());
        }
        File f;
        Vector<String> files = new Vector<String>();
        for (int i = 0; i < list.size(); i++) {
            String item = (String) list.elementAt(i);
            String newPath;
            if (path.equals("."))
                newPath = item;
            else
                newPath = path + File.separator + item;
            logger.debug("   newPath "+newPath);
            if ((f = new File(newPath)).isDirectory() && !newPath.endsWith(".svn"))
                addNodes(currentDir, f);
            else
                files.addElement(item);
        }
        for (int fnum = 0; fnum < files.size(); fnum++)
            if (files.elementAt(fnum).endsWith(".def"))
                currentDir.add(new DefaultMutableTreeNode(files.elementAt(fnum)));
        return currentDir;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddFile;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonLogoff;
    private javax.swing.JButton jButtonLogon;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonRunSelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemFIXSettings;
    private javax.swing.JMenuItem jMenuItemFixLook;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemOrderManager;
    private javax.swing.JMenuItem jMenuItemPreferences;
    private javax.swing.JMenuItem jMenuItemReload;
    private javax.swing.JMenuItem jMenuItemShowFixLog;
    private javax.swing.JMenuItem jMenuItemStartFE;
    private javax.swing.JMenuItem jMenuItemStopFE;
    private javax.swing.JMenuItem jMenuItemTestcaseEdit;
    private javax.swing.JMenuItem jMenuItemViewLog;
    private javax.swing.JMenuItem jMenuLoadTestCases;
    private javax.swing.JMenuItem jMenuSaveSettings;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTable jTableEngineStatus;
    private javax.swing.JTextArea jTestOutput;
    private javax.swing.JTree jTree_testCases;
    // End of variables declaration//GEN-END:variables

}
