/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderManagerGui.java
 *
 * Created on Oct 1, 2010, 12:33:04 AM
 */

package nl.lamia.FixTools;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author marcel
 */
public class OrderManagerGui extends javax.swing.JFrame {

    private OrderManager om=null;

    /** Creates new form OrderManagerGui */
    public OrderManagerGui() {
        initComponents();
        om=OrderManager.get();
        orderTable1.setModel(om.getOrderTable());
        //setup listener for selection change
        ListSelectionModel selModel=orderTable1.getSelectionModel();
        selModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) return;
                ListSelectionModel rowSM = (ListSelectionModel)e.getSource();
                int selectedIndex = rowSM.getMinSelectionIndex();
                if (selectedIndex>=0) {
                    int col0=messageTable.getColumnModel().getColumn(0).getWidth();
                    int col1=messageTable.getColumnModel().getColumn(1).getWidth();
                    int col2=messageTable.getColumnModel().getColumn(2).getWidth();
                    String clordid=(String)orderTable1.getModel().getValueAt(selectedIndex,0);
                    messageTable.setModel(om.getMessageTable(clordid));
                    messageTable.getColumnModel().getColumn(0).setPreferredWidth(col0);
                    messageTable.getColumnModel().getColumn(1).setPreferredWidth(col1);
                    messageTable.getColumnModel().getColumn(2).setPreferredWidth(col2);
                }
            }
        });

        messageTable.setModel(om.getMessageTable(""));
        messageTable.getColumnModel().getColumn(0).setPreferredWidth(110);
        messageTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        messageTable.getColumnModel().getColumn(2).setPreferredWidth(500);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderTable = new javax.swing.JScrollPane();
        orderTable1 = new javax.swing.JTable();
        jButtonRefresh = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTable = messageTable=new javax.swing.JTable()
        {
            @Override
            public boolean isCellEditable(int row,int col) {
                return false;
            }
        };
        jButtonPurge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Order manager");

        orderTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        orderTable1.setGridColor(new java.awt.Color(220, 220, 220));
        orderTable.setViewportView(orderTable1);

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jButtonExit.setText("Close");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        messageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        messageTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        messageTable.setGridColor(new java.awt.Color(220, 220, 220));
        messageTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messageTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(messageTable);

        jButtonPurge.setText("Purge all");
        jButtonPurge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPurgeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(orderTable)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(jButtonPurge)
                            .add(366, 366, 366)
                            .add(jButtonExit)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(jButtonRefresh))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(orderTable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonRefresh)
                    .add(jButtonExit)
                    .add(jButtonPurge))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.setVisible( false );
        this.dispose();    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        orderTable1.setModel(om.getOrderTable());
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonPurgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPurgeActionPerformed
        int result=JOptionPane.showConfirmDialog(this, "All orders and messages will be purged !\n"
                + "This cannot be undone.\nProceed ?", "Confirm purge", JOptionPane.YES_NO_OPTION);
        if (result==JOptionPane.YES_OPTION) {
            om.purgeOrders();
            orderTable1.setModel(om.getOrderTable());
            messageTable.setModel(om.getMessageTable(""));
        }
    }//GEN-LAST:event_jButtonPurgeActionPerformed

    private void messageTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageTableMouseClicked
        if (evt.getClickCount()==2) {
            JTable target = (JTable)evt.getSource();
            int row = target.getSelectedRow();
            String msg=(String)target.getValueAt(row, 2);
            MessageEditor dlg=new MessageEditor(this, true, msg, false);
            dlg.showDialog();
        }
    }//GEN-LAST:event_messageTableMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderManagerGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPurge;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable messageTable;
    private javax.swing.JScrollPane orderTable;
    private javax.swing.JTable orderTable1;
    // End of variables declaration//GEN-END:variables

}
