-- Baseline: the pre-latency schema exactly as it exists on the production H2 DB
-- (messages, orders, test_results WITHOUT the trace columns). On a pre-existing DB this
-- migration is baselined away (never executed) since it already matches; on a fresh DB it
-- builds the starting schema. The latency-tracing feature (trace columns in V2, latency
-- tables in V3) is added on top. Column types mirror Hibernate's H2 output so that
-- spring.jpa.hibernate.ddl-auto=validate passes.

CREATE TABLE IF NOT EXISTS messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    clordid     VARCHAR(20),
    fix_message VARCHAR(2048),
    insert_time TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders (
    clordid     VARCHAR(20) NOT NULL,
    insert_time TIMESTAMP(6),
    status      VARCHAR(30),
    testid      VARCHAR(20),
    PRIMARY KEY (clordid)
);

CREATE TABLE IF NOT EXISTS test_results (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    end_time      TIMESTAMP(6),
    error_message VARCHAR(255),
    log_output    VARCHAR(4096),
    start_time    TIMESTAMP(6),
    success       BOOLEAN NOT NULL,
    test_name     VARCHAR(255),
    PRIMARY KEY (id)
);
