-- Latency-tracing tables (part of the trace feature). These do not exist on the pre-trace
-- production DB, so they are created here rather than in the V1 baseline (which is baselined
-- away on existing DBs). IF NOT EXISTS keeps this a no-op on any DB that already has them.
-- Column types mirror Hibernate's H2 output so spring.jpa.hibernate.ddl-auto=validate passes.

CREATE TABLE IF NOT EXISTS latency_traces (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_tag         INTEGER NOT NULL,
    id_value       VARCHAR(255),
    msg_type       VARCHAR(255),
    send_nanos     BIGINT NOT NULL,
    send_time      TIMESTAMP(6),
    test_result_id BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS latency_trace_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ord_status    VARCHAR(255),
    receive_nanos BIGINT NOT NULL,
    receive_time  TIMESTAMP(6),
    trace_id      BIGINT,
    PRIMARY KEY (id)
);
