#FixTestDriver
#Wed Jan 05 00:20:33 CET 2011
QueuedMessage.staleTime=30000
TestMessage.ignoreUnexpectedTags=false
Window.DictionaryEditor=332,319,702,483
Dictionary.filename=config/products.def
TestMessage.matchClordid=false
TestMessage.matchMsgType=true
TestMessage.skipTags=10,9,45,34,17,37,43,122
Window.OrderManager=487,180,844,607
Application.testcases=testcases
Window.FileViewer=133,64,1074,714
ExpectMessageStep.timeout=6000
Window.FileEditor=263,42,920,751
TestMessage.checkDateTags=true
FixEngine.configuration=config/FixEngine.cfg
Window.MainWindow=253,76,958,621
