#FixTestDriver
#Tue Dec 07 01:18:11 CET 2010
TestMessage.checkDateTags=false
FixEngine.configuration=config/FixEngine.cfg
ExpectMessageStep.timeout=12000
QueuedMessage.staleTime=30000
Application.testcases=testcases
Dictionary.filename=config/products.def
TestMessage.skipTags=10,9,45,34,17,37
TestMessage.ignoreUnexpectedTags=false
